### ISSUE TITLE
How to use AdminLogin ?

### ISSUE THREAD

**Issue by VinBoys** [supercrafter333/AdminLogin#1]
Pls tell me how to use AdminLogin StepByStep

**Comment by supercrafter333** [comment]
Okay, here's a Step-By-Step list:

1. Go to the vonfig of AdminLogin
2. Go to `config.yml`
3. Add new entry like the other entrys

Example:
```yml
Owner:
  code: "ownerx6859430"
Admin:
  code: "adminx6584317"
Developer:
  code: "developerx776"
YourNewGroup:
  code: "code for group"
```

I hope that that helped you. 😁
